### PR TITLE
Moved Dropbox files to GitHub

### PR DESCRIPTION
**Pull request by Doregon**
They're in the src/ModioX/Database folder, but it's pretty straightforward to edit this by going into the "Urls.cs" file and changing the directory that's in the link. If I've missed any files, let me know so I can fix them.

Also (this isn't part of the pull request) I own the r/the_new_ps3_homebrew subreddit and when I came across this I thought it was pretty cool. Would you allow me to document this program so I could put it and some links leading here on the wiki for that subreddit?

### CODE REVIEW

**Comment by KayGart** [comment]
I'd still prefer if the databases where in an actual database even if that database is local and downloaded on startup, but this looks good for now.

**Comment by ohhsodead** [comment]
@Doregon thanks for contribution bro! I'll be on soon so will double check everything and merge it. But this will definitely free up a lot of storage on my Dropbox lmao

**Comment by ohhsodead** [comment]
@KayGart bro tbh I'd never worked with actual databases, so will need a lot of help for that. However, I'll do some research to convert these JSON files into one as should it should be fairly straightforward ig

**Comment by KayGart** [comment]
We already have the classes for the data, so we can simply use Entity Framework to do the heavy lifting.

**Comment by ohhsodead** [comment]
@Doregon sorry, forgot about your last commit but yeah ofc that's not problem. I appreciate it!

**Comment by ohhsodead** [comment]
@KayGart alright seems simple enough ig let's chat on discord later when u can and go through the basics with me please (:

**Comment by Doregon** [comment]
@ohhsodead I’ve worked on databases before, so I might be able to check that out, I’m just busy working on Dynmap’s async functionality at the moment.

**Comment by ohhsodead** [comment]
@Doregon do u have discord? can chat there whenever u free.

**Comment by Doregon** [comment]
Yeah I do, it’s Doregon#3091.

**Comment by ohhsodead** [comment]
@Doregon can't find it bro..

**Comment by ohhsodead** [comment]
@Doregon mine is ohhsodead#2519

**Pull request merged**
